---
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = "hide")
library(dplyr)
library(ggplot2)
library(ggthemes)
library(scales)
```

```{r}
education = read.csv("EducationData.csv", header = TRUE)
summary(education)
```

The below summary of the data, and following histograms, show that the distributions of the two samples are not normal, and the samples have substantially different standard deviations and sample sizes. Thus, an ordinary t-test would not be valid.    

```{r, echo = TRUE, results = "markup"}
education %>% group_by(Educ) %>% summarize(mean_income = mean(Income2005), sd_income = sd(Income2005), count = n())
```

---

```{r}
education %>% ggplot(aes(x = Income2005)) +
  geom_histogram(color = "blue") +
  facet_wrap(~Educ) +
  theme_economist() +
  scale_x_continuous(labels = scales::comma) +
  labs(
    title = "Income Distribution by Education Level",
    x = "Income",
    y = "Education Level"
  )
```

---

In such a case, Welch's t-test can be used.

```{r, echo = TRUE, results = "markup"}
t.test(Income2005 ~ Educ, data = education, var.equal = FALSE)
```